steps:
  - name: hashicorp/terraform:1.7.5
    id: Terraform Init
    entrypoint: sh
    args:
      - -c
      - |
        terraform init

  - name: hashicorp/terraform:1.7.5
    id: Terraform Plan
    entrypoint: sh
    args:
      - -c
      - |
        terraform plan -out=tfplan

  - name: hashicorp/terraform:1.7.5
    id: Terraform Apply
    entrypoint: sh
    args:
      - -c
      - |
        terraform apply -auto-approve tfplan